name: Tests

on:
  push:
    branches:
      - main
      - dev
      - 'feature/*'
      - 'hotfix/*'
      - 'release/*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run Tests
        run: mvn test
